# Server
server.port=8083

# Spring Application
spring.application.name=doctor-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/doctor_db
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:rumiche}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

# Actuator Endpoints (Management)
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
