server.port=8761
spring.application.name=eureka-server

# El servidor Eureka no se registra ni se descubre a si mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}

management.endpoints.web.exposure.include=health,info,prometheus
